# _config.yml
title: Shape Bias & Robustness
email: your-email@example.com
description: >-
  Project site exploring shape bias and robustness in image classification and segmentation.

url: "https://marcoschumacher-uniwuppertal.github.io"
baseurl: "/Shape-Bias-and-Robustness-Evaluation-via-Cue-Decomposition-for-Image-Classification-and-Segmentation"

# use the remote_theme approach
remote_theme: "mmistakes/minimal-mistakes@4.24.0"  # pin to a release if you like
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "Marco Schumacher"
  avatar: "/assets/images/avatar.png"
  bio: "Researcher exploring visual cues in deep learning."
  location: "Wuppertal, Germany"
