title: Shape Bias & Robustness
email: your-email@example.com
description: >-
  Project site exploring shape bias and robustness in image classification and segmentation.

url: "https://marcoschumacher-uniwuppertal.github.io"
baseurl: "/Shape-Bias-and-Robustness-Evaluation-via-Cue-Decomposition-for-Image-Classification-and-Segmentation"

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-remote-theme

author:
  name: "Marco Schumacher"
  avatar: "/assets/images/avatar.png" # Optional: add your own image
  bio: "Researcher exploring visual cues in deep learning."
  location: "Wuppertal, Germany"

# Optional: disable things you're not using yet
collections: []
paginate: 5
