# _config.yml
title: Shape Bias & Robustness
email: your-email@example.com
description: >-
  Project site exploring shape bias and robustness in image classification and segmentation.

url: "https://marcoschumacher-uniwuppertal.github.io"
baseurl: "/Shape-Bias-and-Robustness-Evaluation-via-Cue-Decomposition-for-Image-Classification-and-Segmentation"


theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "Marco Schumacher"
  avatar: "/assets/images/avatar.png"
  bio: "Researcher exploring visual cues in deep learning."
  location: "Wuppertal, Germany"
